include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore
    use_super_parameters: ignore
